### ISSUE TITLE
Uncaught TypeError: Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by flautrup** [whoisthecoon/atom-fold-search-results#2]
[Enter steps to reproduce below:]

1. The error pops up directly when I run a search

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [fold-search-results](https://github.com/whoisthecoon/atom-fold-search-results) package, v1.0.4

### Stack Trace

Uncaught TypeError: Cannot read property 'constructor' of undefined

```
At /Users/flp/.atom/packages/fold-search-results/lib/ToggleSearchResults.js:39

TypeError: Cannot read property 'constructor' of undefined
    at MutationObserver.<anonymous> (/Users/flp/.atom/packages/fold-search-results/lib/ToggleSearchResults.js:39:25)
```

### Commands

```
     -2:23.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:04.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
fold-search-results, v1.0.4
hyperclick, v0.0.35
js-hyperclick, v1.4.1
node-debugger, v1.4.3

# Dev
No dev packages
```

**Comment by whoisthecoon** [comment]
Hi,

I couldn't reproduce the problem. Can you tell me what version of the "find-and-replace" package is installed on your Atom?

**Comment by lijay** [comment]
Hi, 

I have the same issue on 1.0.4.
It can be reproduced by the steps below.
1. search all files by keyword
2. folding the search result
3. search another keyword

**Comment by flautrup** [comment]
Im using 0.195.0 of find-and-replace

**Comment by whoisthecoon** [comment]
It seems to be fixed, thanks you two!
